### ISSUE TITLE
Home page navigation buttons too big

### ISSUE THREAD

**Issue by DarkEyeDragon** [codevision-org/codevision-web#11]
![image](https://user-images.githubusercontent.com/6131099/48437820-ae401480-e782-11e8-8ef1-77f441ca97bc.png)

I feel like these are way to big. Even blind people could read them.

**Comment by Technerder** [comment]
Added the medium priority label because the main site is the first thing someone sees when they go to the site.

**Comment by stefvanschie** [comment]
The issue currently has both priority low and medium, one of those should probably be removed to avoid ambiguity on the issue's current priority status.

**Comment by DarkEyeDragon** [comment]
Addressed in commit https://github.com/codevision-org/codevision-web/commit/828c55c6c9c6837c260d2d0761caee1253022e95
